### ISSUE TITLE
Load project problem 

### ISSUE THREAD

**Issue by agneroalain** [sonusindhu/Laravel-5-simple-website#1]
Hi i try to launch your project but i got this error , 
Can you tell me how fix it ? 

![capture](https://user-images.githubusercontent.com/17789004/36737672-ecfe3134-1bdb-11e8-8e24-653fd0ecce2e.JPG)

**Comment by sonusindhu** [comment]
Have you used `composer install` after download the codebase ?
You need to do the following:

Clone the repo
`composer install`
rename the .env.example to .env
`php artisan key:generate`

let me know if you need further assistance
